name: CI
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build & test (Maven)
        run: ./mvnw -B -ntp verify

      # Optional: ensure Dockerfile builds (no push)
      - name: Docker build smoke
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: library-catalog:test
